name: Run Python Script

on:
  workflow_dispatch:


env:
  YOUTUBE_API: ${{ secrets.YOUTUBE_API }} 

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
      uses: actions/checkout@v3
      name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
      name: Run Python Script 
      run: |
        pip install -r requirements.txt 
        python manage.py

