name: My Workflow

on:
  push:
    branches:
      - '*'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: My Step
        env:
          YOUTUBE_API: ${{ secrets.YOUTUBE_API }} 
        run: |
          pip install -r YtCmntAnalysis/requirements.txt
          python YtCmntAnalysis/Analysis/ML/sent_analysis.py    