name: My Workflow

on:
  push:
    branches:
      - '*'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: My Step
        env:
          YOUTUBE_API: ${{ secrets.YOUTUBE_API }} 
        run: python Trust-Me-Bro/YtCmntAnalysis/Analysis/ML/sent_analysis.py    