name: Run Python Script

on:
  workflow_dispatch:


env:
  YOUTUBE_API: ${{ secrets.YOUTUBE_API }} 

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
